### ISSUE TITLE
Screen blanks when out of focus

### ISSUE THREAD

**Issue by Areku-The-OF** [Flowit-Game/Flowit#27] opened 2022-10-30 19:32 UTC
When playing the game, if I change apps or go to the launcher the screen becomes blank and the only way to play is to close the app and open it again.

Version 3.3 downloaded from F-Droid
Android 13 on Pixel 7

![4531b393-5e73-481f-a8d3-800cf9ea7c7b](https://user-images.githubusercontent.com/73086862/198897917-1fcaf44a-bfa5-45c5-917f-88c27a8332b8.gif)

**Comment by tibob** [comment] 2022-11-17 18:19
This is a Duplicate of #18

**Closed** 2022-11-18 17:24 UTC
